import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

DB_URL = os.environ.get("SUPABASE_DB_URL")

sql_script = """
-- أولاً: إنشاء الجداول الأساسية

-- 1. جدول المستخدمين (Profiles) المرتبط بنظام المصادقة (Auth)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  role TEXT DEFAULT 'writer',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. جدول الإعدادات (Settings)
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. جدول الأطباء والخبراء (Doctors / Experts)
CREATE TABLE IF NOT EXISTS doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  role_ar TEXT,
  role_en TEXT,
  img TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 4. جدول المنتجات (Products)
CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  category TEXT,
  main_image TEXT,
  images JSONB,
  overview_ar TEXT,
  overview_en TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 5. جدول المقالات (Articles)
CREATE TABLE IF NOT EXISTS articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_key TEXT,
  category_key TEXT,
  excerpt_key TEXT,
  img TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 6. جدول البوسترات (Posters)
CREATE TABLE IF NOT EXISTS posters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_key TEXT,
  img TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- ثانياً: تفعيل نظام الحماية RLS (Row Level Security)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE posters ENABLE ROW LEVEL SECURITY;

-- ثالثاً: وضع سياسات القراءة (للزوار) - لكي يمكن للجميع القراءة بدون تسجيل دخول
DO $$
BEGIN
    DROP POLICY IF EXISTS "Allow public read access for settings" ON settings;
    CREATE POLICY "Allow public read access for settings" ON settings FOR SELECT USING (true);
    
    DROP POLICY IF EXISTS "Allow public read access for doctors" ON doctors;
    CREATE POLICY "Allow public read access for doctors" ON doctors FOR SELECT USING (true);
    
    DROP POLICY IF EXISTS "Allow public read access for products" ON products;
    CREATE POLICY "Allow public read access for products" ON products FOR SELECT USING (true);
    
    DROP POLICY IF EXISTS "Allow public read access for profiles" ON profiles;
    CREATE POLICY "Allow public read access for profiles" ON profiles FOR SELECT USING (true);

    DROP POLICY IF EXISTS "Allow public read access for articles" ON articles;
    CREATE POLICY "Allow public read access for articles" ON articles FOR SELECT USING (true);

    DROP POLICY IF EXISTS "Allow public read access for posters" ON posters;
    CREATE POLICY "Allow public read access for posters" ON posters FOR SELECT USING (true);
END $$;

-- رابعاً: سياسات الإضافة والتعديل والحذف (للمدراء والكتّاب فقط) - تتطلب Auth
DO $$
BEGIN
    DROP POLICY IF EXISTS "Allow authenticated users to insert settings" ON settings;
    CREATE POLICY "Allow authenticated users to insert settings" ON settings FOR INSERT TO authenticated WITH CHECK (true);
    
    DROP POLICY IF EXISTS "Allow authenticated users to update settings" ON settings;
    CREATE POLICY "Allow authenticated users to update settings" ON settings FOR UPDATE TO authenticated USING (true);
    
    DROP POLICY IF EXISTS "Allow authenticated users to delete settings" ON settings;
    CREATE POLICY "Allow authenticated users to delete settings" ON settings FOR DELETE TO authenticated USING (true);

    DROP POLICY IF EXISTS "Allow authenticated users to insert doctors" ON doctors;
    CREATE POLICY "Allow authenticated users to insert doctors" ON doctors FOR INSERT TO authenticated WITH CHECK (true);
    
    DROP POLICY IF EXISTS "Allow authenticated users to update doctors" ON doctors;
    CREATE POLICY "Allow authenticated users to update doctors" ON doctors FOR UPDATE TO authenticated USING (true);
    
    DROP POLICY IF EXISTS "Allow authenticated users to delete doctors" ON doctors;
    CREATE POLICY "Allow authenticated users to delete doctors" ON doctors FOR DELETE TO authenticated USING (true);

    DROP POLICY IF EXISTS "Allow authenticated users to insert products" ON products;
    CREATE POLICY "Allow authenticated users to insert products" ON products FOR INSERT TO authenticated WITH CHECK (true);
    
    DROP POLICY IF EXISTS "Allow authenticated users to update products" ON products;
    CREATE POLICY "Allow authenticated users to update products" ON products FOR UPDATE TO authenticated USING (true);
    
    DROP POLICY IF EXISTS "Allow authenticated users to delete products" ON products;
    CREATE POLICY "Allow authenticated users to delete products" ON products FOR DELETE TO authenticated USING (true);

    DROP POLICY IF EXISTS "Allow authenticated users to insert articles" ON articles;
    CREATE POLICY "Allow authenticated users to insert articles" ON articles FOR INSERT TO authenticated WITH CHECK (true);
    DROP POLICY IF EXISTS "Allow authenticated users to update articles" ON articles;
    CREATE POLICY "Allow authenticated users to update articles" ON articles FOR UPDATE TO authenticated USING (true);
    DROP POLICY IF EXISTS "Allow authenticated users to delete articles" ON articles;
    CREATE POLICY "Allow authenticated users to delete articles" ON articles FOR DELETE TO authenticated USING (true);

    DROP POLICY IF EXISTS "Allow authenticated users to insert posters" ON posters;
    CREATE POLICY "Allow authenticated users to insert posters" ON posters FOR INSERT TO authenticated WITH CHECK (true);
    DROP POLICY IF EXISTS "Allow authenticated users to update posters" ON posters;
    CREATE POLICY "Allow authenticated users to update posters" ON posters FOR UPDATE TO authenticated USING (true);
    DROP POLICY IF EXISTS "Allow authenticated users to delete posters" ON posters;
    CREATE POLICY "Allow authenticated users to delete posters" ON posters FOR DELETE TO authenticated USING (true);

    DROP POLICY IF EXISTS "Allow authenticated users to update their own profile" ON profiles;
    CREATE POLICY "Allow authenticated users to update their own profile" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id);
END $$;
"""

def install_supabase_schema():
    if not DB_URL:
        print("❌ لم يتم العثور على رابط قاعدة البيانات!")
        print("افتح ملف .env وأضف رابط قاعدة البيانات (تأكد من استبدال [YOUR-PASSWORD] بكلمة مرور الـ Database):")
        print('SUPABASE_DB_URL="postgresql://postgres.jszubagkmmrjafseooft:[YOUR-PASSWORD]@aws-0-eu-central-1.pooler.supabase.com:6543/postgres"')
        return

    print("جاري الاتصال بقاعدة بيانات Supabase...")
    try:
        conn = psycopg2.connect(DB_URL)
        conn.autocommit = True
        cursor = conn.cursor()
        
        print("جاري إنشاء الجداول (profiles, settings, doctors, products) وتطبيق قواعد الأمان RLS...")
        cursor.execute(sql_script)
        
        print("✅ تم إنشاء وتجهيز الجداول بنجاح!")
        cursor.close()
        conn.close()
    except Exception as e:
        print(f"❌ حدث خطأ أثناء تنفيذ أكواد الـ SQL: \n{e}")

if __name__ == "__main__":
    install_supabase_schema()
