import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

DB_URL = os.getenv("SUPABASE_DB_URL")

sql_script = """
-- 1. جدول الحسابات (Profiles)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  role TEXT DEFAULT 'writer', -- admin, publisher, writer
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. جدول الإعدادات (Settings)
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value JSONB,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. جدول الأطباء والخبراء (Doctors)
CREATE TABLE IF NOT EXISTS doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  role_ar TEXT,
  role_en TEXT,
  img TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 4. جدول المنتجات (Products)
CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  category TEXT,
  main_image TEXT,
  images JSONB,
  overview_ar TEXT,
  overview_en TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 5. جدول المقالات (Articles)
CREATE TABLE IF NOT EXISTS articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_ar TEXT NOT NULL,
  title_en TEXT NOT NULL,
  content_ar TEXT,
  content_en TEXT,
  category TEXT,
  image TEXT,
  author_id UUID REFERENCES profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 6. جدول البوسترات (Posters)
CREATE TABLE IF NOT EXISTS posters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_ar TEXT,
  title_en TEXT,
  image TEXT NOT NULL,
  type TEXT DEFAULT 'education', -- education, campaign, news
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- تفعيل RLS (Row Level Security) - Disabled temporarily for migration
-- تفعيل RLS (Row Level Security)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE posters ENABLE ROW LEVEL SECURITY;

-- سياسات الوصول (Policies)
DO $$
BEGIN
    -- Profiles
    DROP POLICY IF EXISTS "Allow public read access for profiles" ON profiles;
    CREATE POLICY "Allow public read access for profiles" ON profiles FOR SELECT USING (true);
    
    -- Settings
    DROP POLICY IF EXISTS "Allow public read access for settings" ON settings;
    CREATE POLICY "Allow public read access for settings" ON settings FOR SELECT USING (true);
    
    -- Doctors
    DROP POLICY IF EXISTS "Allow public read access for doctors" ON doctors;
    CREATE POLICY "Allow public read access for doctors" ON doctors FOR SELECT USING (true);
    DROP POLICY IF EXISTS "Allow authenticated users to insert doctors" ON doctors;
    CREATE POLICY "Allow authenticated users to insert doctors" ON doctors FOR INSERT TO authenticated WITH CHECK (true);
    DROP POLICY IF EXISTS "Allow authenticated users to update doctors" ON doctors;
    CREATE POLICY "Allow authenticated users to update doctors" ON doctors FOR UPDATE TO authenticated USING (true);
    DROP POLICY IF EXISTS "Allow authenticated users to delete doctors" ON doctors;
    CREATE POLICY "Allow authenticated users to delete doctors" ON doctors FOR DELETE TO authenticated USING (true);

    -- Products
    DROP POLICY IF EXISTS "Allow public read access for products" ON products;
    CREATE POLICY "Allow public read access for products" ON products FOR SELECT USING (true);
    DROP POLICY IF EXISTS "Allow authenticated users to insert products" ON products;
    CREATE POLICY "Allow authenticated users to insert products" ON products FOR INSERT TO authenticated WITH CHECK (true);
    DROP POLICY IF EXISTS "Allow authenticated users to update products" ON products;
    CREATE POLICY "Allow authenticated users to update products" ON products FOR UPDATE TO authenticated USING (true);
    DROP POLICY IF EXISTS "Allow authenticated users to delete products" ON products;
    CREATE POLICY "Allow authenticated users to delete products" ON products FOR DELETE TO authenticated USING (true);

    -- Articles
    DROP POLICY IF EXISTS "Allow public read access for articles" ON articles;
    CREATE POLICY "Allow public read access for articles" ON articles FOR SELECT USING (true);
    DROP POLICY IF EXISTS "Allow authenticated users to insert articles" ON articles;
    CREATE POLICY "Allow authenticated users to insert articles" ON articles FOR INSERT TO authenticated WITH CHECK (true);

    -- Posters
    DROP POLICY IF EXISTS "Allow public read access for posters" ON posters;
    CREATE POLICY "Allow public read access for posters" ON posters FOR SELECT USING (true);
    DROP POLICY IF EXISTS "Allow authenticated users to update posters" ON posters;
    CREATE POLICY "Allow authenticated users to update posters" ON posters FOR UPDATE TO authenticated USING (true);
    DROP POLICY IF EXISTS "Allow authenticated users to delete posters" ON posters;
    CREATE POLICY "Allow authenticated users to delete posters" ON posters FOR DELETE TO authenticated USING (true);

    DROP POLICY IF EXISTS "Allow authenticated users to update their own profile" ON profiles;
    CREATE POLICY "Allow authenticated users to update their own profile" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id);
END $$;
"""

def install_supabase_schema():
    if not DB_URL:
        print("❌ لم يتم العثور على رابط قاعدة البيانات!")
        return

    try:
        conn = psycopg2.connect(DB_URL)
        cur = conn.cursor()
        print("جاري تهيئة قاعدة البيانات...")
        cur.execute(sql_script)
        conn.commit()
        cur.close()
        conn.close()
        print("✅ تمت تهيئة قاعدة البيانات بنجاح!")
    except Exception as e:
        print(f"❌ خطأ في الاتصال بقاعدة البيانات: {e}")

if __name__ == "__main__":
    install_supabase_schema()
